language: python
python:
  - "3.5"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
# command to install dependencies
install: make setup
# # command to run tests
script: pipenv shell -c "python3 setup.py test"
